/**
 * Kerala Temple Events Seed Script
 * Run: MONGO_URI=<your_uri> node seeds/keralaTempleEvents.js
 * Or:  node seeds/keralaTempleEvents.js  (uses backend/.env MONGO_URI)
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Event = require('../models/Event');

const MONGO_URI = process.env.MONGO_URI;

// ─── 20 Realistic Kerala Temple Events ──────────────────────────────────────

const events = [
  {
    name: 'Guruvayur Ekadasi Mahotsavam 2025',
    description: 'Guruvayur Ekadasi is one of the most sacred and auspicious days at Sri Krishna Temple, Guruvayur. Lakhs of devotees throng the temple for special Ekadasi poojas, elephant procession, and Vilakku. The 24-hour continuous archana, Udayasthamana Pooja, and the majestic caparisoned elephant procession with Panchavadyam make this a truly divine experience. Fasting and all-night bhajan sessions are observed by devotees across Kerala.',
    date: new Date('2025-11-01T04:00:00+05:30'),
    endDate: new Date('2025-11-02T22:00:00+05:30'),
    location: {
      address: 'Sri Krishna Temple, Guruvayur, Thrissur, Kerala 680101',
      district: 'Thrissur',
      lat: 10.5943,
      lng: 76.0421,
      placeName: 'Guruvayur Sri Krishna Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Guruvayur_Temple.jpg/1200px-Guruvayur_Temple.jpg'],
    crowd: 'high',
    attendees: 500000,
    trending: true,
    organizerName: 'Guruvayur Devaswom Board',
    organizerPhone: '+91-487-2556236',
    website: 'https://guruvayurdevaswom.in',
    status: 'approved',
    tags: ['guruvayur', 'ekadasi', 'krishna', 'kerala-temple', 'AI'],
  },
  {
    name: 'Sabarimala Mandalam-Makaravilakku Season 2025',
    description: 'The annual Mandalam-Makaravilakku pilgrimage season at Sabarimala Sree Dharma Sastha Temple is one of the largest Hindu pilgrimages in the world. Millions of Ayyappa devotees undertake the 41-day Mandala vrat and trek through the forest to seek blessings. The season culminates on Makaravilakku — when the celestial star Makara Jyothi appears and the sacred arrow (Thiruvabharanam) arrives in a grand procession. Devotees wear black attire and observe strict penance before undertaking the pilgrimage.',
    date: new Date('2025-11-26T05:00:00+05:30'),
    endDate: new Date('2026-01-14T23:00:00+05:30'),
    location: {
      address: 'Sabarimala Sree Dharma Sastha Temple, Pathanamthitta, Kerala 689589',
      district: 'Pathanamthitta',
      lat: 9.3833,
      lng: 77.0833,
      placeName: 'Sabarimala Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Sabarimala_temple.jpg/1200px-Sabarimala_temple.jpg'],
    crowd: 'high',
    attendees: 3000000,
    trending: true,
    organizerName: 'Travancore Devaswom Board',
    organizerPhone: '+91-471-2314288',
    website: 'https://www.sabarimalatemple.com',
    status: 'approved',
    tags: ['sabarimala', 'ayyappa', 'mandalam', 'makaravilakku', 'AI'],
  },
  {
    name: 'Attukal Pongala Mahotsavam 2026',
    description: 'Attukal Pongala is the largest annual gathering of women in the world, stretching across 15 km of streets in Thiruvananthapuram. Millions of women prepare the sacred Pongala offering — rice cooked in jaggery — on makeshift earthen stoves. The Guinness World Record holder festival honours Attukal Devi (Kannaki) and spans from the 9th to 17th day of the Karthika month. The streets transform into a sea of devotion as women from all faiths offer the pongala with prayers for family wellbeing.',
    date: new Date('2026-03-02T05:30:00+05:30'),
    endDate: new Date('2026-03-10T22:00:00+05:30'),
    location: {
      address: 'Attukal Devi Temple, Attukal, Thiruvananthapuram, Kerala 695001',
      district: 'Thiruvananthapuram',
      lat: 8.4823,
      lng: 76.9465,
      placeName: 'Attukal Bhagavathy Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Attukal_Pongala_2017.jpg/1200px-Attukal_Pongala_2017.jpg'],
    crowd: 'high',
    attendees: 2500000,
    trending: true,
    organizerName: 'Attukal Devaswom',
    organizerPhone: '+91-471-2460327',
    website: 'https://www.attukaltemple.org',
    status: 'approved',
    tags: ['attukal', 'pongala', 'women', 'guinness-record', 'AI'],
  },
  {
    name: 'Thrissur Pooram 2026',
    description: 'Thrissur Pooram is the greatest temple festival in Kerala and arguably one of the most spectacular cultural events in India. Held annually at the Vadakkunnathan Temple ground in Thrissur, the festival is a competition between two temple groups — Thiruvambadi and Paramekkavu — each presenting grand elephant processions adorned with golden caparisons (nettipattam). The highlight is the Kudamattam (exchange of ornate parasols) and the thrilling Vedikettu (fireworks display). The event draws over a million visitors each year.',
    date: new Date('2026-04-26T05:00:00+05:30'),
    endDate: new Date('2026-04-27T06:00:00+05:30'),
    location: {
      address: 'Vadakkunnathan Temple, Thrissur, Kerala 680001',
      district: 'Thrissur',
      lat: 10.5276,
      lng: 76.2144,
      placeName: 'Vadakkunnathan Temple Maidan',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Thrissur_Pooram_2013.jpg/1200px-Thrissur_Pooram_2013.jpg'],
    crowd: 'high',
    attendees: 1000000,
    trending: true,
    organizerName: 'Thiruvambadi & Paramekkavu Devaswom',
    organizerPhone: '+91-487-2422752',
    website: 'https://thrissurpooram.in',
    status: 'approved',
    tags: ['thrissur-pooram', 'elephants', 'panchavadyam', 'kerala', 'AI'],
  },
  {
    name: 'Padmanabhaswamy Temple Alpashy Festival 2025',
    description: 'The Alpashy Utsavam at Sree Padmanabhaswamy Temple, one of the 108 Divya Desams and the wealthiest temple in the world by assets, is a 10-day grand festival celebrated in the Malayalam month of Thulam. The festival features elaborate bhajans, Harikathas, classical Carnatic music concerts, and stunning decorations of the temple gopuram with lights. The sacred idol of Lord Padmanabha (Vishnu in Anantha Shayana posture) receives special abhishekam and alankaram during all ten days. Only Hindus are permitted to enter the inner sanctum.',
    date: new Date('2025-10-16T05:00:00+05:30'),
    endDate: new Date('2025-10-25T22:00:00+05:30'),
    location: {
      address: 'Sree Padmanabhaswamy Temple, East Fort, Thiruvananthapuram, Kerala 695023',
      district: 'Thiruvananthapuram',
      lat: 8.4823,
      lng: 76.9467,
      placeName: 'Padmanabhaswamy Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Padmanabhaswamy_temple.jpg/1200px-Padmanabhaswamy_temple.jpg'],
    crowd: 'high',
    attendees: 150000,
    trending: false,
    organizerName: 'Travancore Royal Family & Devaswom',
    organizerPhone: '+91-471-2450233',
    website: 'https://www.sreepadmanabhaswamytemple.org',
    status: 'approved',
    tags: ['padmanabhaswamy', 'thiruvananthapuram', 'vishnu', 'utsavam', 'AI'],
  },
  {
    name: 'Chottanikkara Bhagavathy Makam Thozhal 2026',
    description: 'The Makam Thozhal (Makam star worship) at Chottanikkara Bhagavathy Temple is a highly sacred event observed on each Makam nakshatra day. The temple, dedicated to Goddess Rajeshwari (Bhagavathy), is one of the most important Shakti temples in Kerala. Tens of thousands of devotees offer Guruti (camphor flame) and participate in the procession of the goddess. The evening Sreebhuta Bali and the illumination of the full temple complex create a profoundly spiritual atmosphere. Special healing rituals for mental wellness are also conducted.',
    date: new Date('2026-02-04T04:00:00+05:30'),
    endDate: new Date('2026-02-04T22:00:00+05:30'),
    location: {
      address: 'Chottanikkara Bhagavathy Temple, Chottanikkara, Ernakulam, Kerala 682312',
      district: 'Ernakulam',
      lat: 9.9855,
      lng: 76.4198,
      placeName: 'Chottanikkara Temple',
    },
    category: 'Cultural',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Chottanikkara_temple.jpg/1200px-Chottanikkara_temple.jpg'],
    crowd: 'high',
    attendees: 80000,
    trending: false,
    organizerName: 'Chottanikkara Devaswom',
    organizerPhone: '+91-484-2690766',
    status: 'approved',
    tags: ['chottanikkara', 'bhagavathy', 'shakti', 'AI'],
  },
  {
    name: 'Vaikom Ashtami Rohini Festival 2025',
    description: 'The Ashtami Rohini (Janmashtami) celebration at Vaikom Mahadeva Temple — one of the 5 Pancha Mahadeva Temples of Kerala — is an 8-day grand utsavam. Lord Shiva is worshipped in the rare Swayambhu Lingam form here, making this temple extraordinarily important. The Rohini nakshatra day sees special milk abhishekam (Ksheera Abhishekam), elephant procession, Panchavadyam, and grand illumination. The cool breeze from Vembanad Lake nearby adds to the serene ambiance.',
    date: new Date('2025-08-16T04:30:00+05:30'),
    endDate: new Date('2025-08-23T22:00:00+05:30'),
    location: {
      address: 'Vaikom Mahadeva Temple, Vaikom, Kottayam, Kerala 686141',
      district: 'Kottayam',
      lat: 9.7508,
      lng: 76.3954,
      placeName: 'Vaikom Mahadeva Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Vaikom_Temple.jpg/1200px-Vaikom_Temple.jpg'],
    crowd: 'high',
    attendees: 200000,
    trending: false,
    organizerName: 'Vaikom Devaswom',
    organizerPhone: '+91-481-2362205',
    status: 'approved',
    tags: ['vaikom', 'shiva', 'ashtami', 'rohini', 'panchamahadevas', 'AI'],
  },
  {
    name: 'Kadampuzha Devi Utsavam 2025',
    description: 'Kadampuzha Devi Temple in Malappuram is one of the most powerful Shakti shrines in Kerala, dedicated to Goddess Kadampuzha Amma — a manifestation of Durga. The annual Utsavam is a 10-day festival during Karkidakam month, featuring Theyyam performances, Thidambu Nritham, Ottanthullal, and famous Gajakesariyogam (lord with elephant). The temple is uniquely situated in a dense forest by the Kadampuzha River, making the festival atmosphere deeply mystical. Devotees from across Malappuram and Kozhikode districts participate in large numbers.',
    date: new Date('2025-07-20T05:00:00+05:30'),
    endDate: new Date('2025-07-29T22:00:00+05:30'),
    location: {
      address: 'Kadampuzha Devi Temple, Kadampuzha, Malappuram, Kerala 676541',
      district: 'Malappuram',
      lat: 11.0247,
      lng: 76.0712,
      placeName: 'Kadampuzha Bhagavathy Temple',
    },
    category: 'Cultural',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Kadampuzha_Devi_Temple.jpg/1200px-Kadampuzha_Devi_Temple.jpg'],
    crowd: 'high',
    attendees: 120000,
    trending: false,
    organizerName: 'Kadampuzha Devaswom',
    status: 'approved',
    tags: ['kadampuzha', 'devi', 'shakti', 'malappuram', 'AI'],
  },
  {
    name: 'Koodalmanikyam Bharani Festival 2025',
    description: 'The Bharani Utsavam at Koodalmanikyam Temple, Irinjalakuda — dedicated to Bharata (brother of Lord Rama) — is unique as this is believed to be the only temple in the world where Bharata is the principal deity. The Bharani festival, held once a year during the Bharani nakshatra in the Malayalam month of Karkidakam, draws enormous crowds for the spectacular Bharani Vilakku (lamp festival). Tens of thousands of oil lamps are lit across the temple complex creating a breathtaking spectacle.',
    date: new Date('2025-07-28T17:00:00+05:30'),
    endDate: new Date('2025-07-29T06:00:00+05:30'),
    location: {
      address: 'Koodalmanikyam Temple, Irinjalakuda, Thrissur, Kerala 680121',
      district: 'Thrissur',
      lat: 10.3426,
      lng: 76.2135,
      placeName: 'Koodalmanikyam Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Koodalmanikyam_Temple.jpg/1200px-Koodalmanikyam_Temple.jpg'],
    crowd: 'high',
    attendees: 300000,
    trending: false,
    organizerName: 'Koodalmanikyam Devaswom',
    organizerPhone: '+91-480-2826285',
    status: 'approved',
    tags: ['koodalmanikyam', 'bharata', 'bharani', 'irinjalakuda', 'AI'],
  },
  {
    name: 'Sree Mahadeva Temple Arattu — Ettumanoor 2025',
    description: 'The Ettumanoor Mahadeva Temple, renowned for its exquisite Padmavyooha murals, celebrates a 10-day Utsavam culminating with the grand Arattu procession. The famous "Ezharaponana" gold canopy weighing 7.5 kilograms adorns the deity during the festival days. On the 8th day (Ashtami), a spectacular fireworks display and Panchavadyam performance lasting several hours takes place. The Arattu (ritual bathing of the idol) on the 10th day at a nearby pond is witnessed by thousands of believers who consider it highly sacred.',
    date: new Date('2025-02-14T05:00:00+05:30'),
    endDate: new Date('2025-02-23T22:00:00+05:30'),
    location: {
      address: 'Ettumanoor Mahadeva Temple, Ettumanoor, Kottayam, Kerala 686631',
      district: 'Kottayam',
      lat: 9.6697,
      lng: 76.5566,
      placeName: 'Ettumanoor Mahadeva Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ettumanoor_Mahadeva_temple.jpg/1200px-Ettumanoor_Mahadeva_temple.jpg'],
    crowd: 'high',
    attendees: 100000,
    trending: false,
    organizerName: 'Ettumanoor Devaswom Board',
    organizerPhone: '+91-481-2563242',
    status: 'approved',
    tags: ['ettumanoor', 'mahadeva', 'shiva', 'arattu', 'kottayam', 'AI'],
  },
  {
    name: 'Kollam Asramam Sree Krishna Temple Utsavam 2025',
    description: 'The annual 7-day Utsavam at Asramam Sree Krishna Temple in Kollam is celebrated with great devotion during the Malayalam month of Vrischikam. Highlights include Panchavadyam, illuminated procession with caparisoned elephants, classical Kathakali and Mohiniyattam performances, and grand Deeparadhana every evening. Located near the scenic Ashtamudi backwaters, the temple grounds turn into a grand cultural hub during the festival. Boat processions on the lake with illuminated crafts are an added attraction unique to this temple.',
    date: new Date('2025-12-05T05:00:00+05:30'),
    endDate: new Date('2025-12-11T22:00:00+05:30'),
    location: {
      address: 'Asramam Sree Krishna Temple, Asramam, Kollam, Kerala 691002',
      district: 'Kollam',
      lat: 8.8876,
      lng: 76.5827,
      placeName: 'Asramam Krishna Temple, Kollam',
    },
    category: 'Cultural',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Ashtamudi_lake.jpg/1200px-Ashtamudi_lake.jpg'],
    crowd: 'medium',
    attendees: 50000,
    trending: false,
    organizerName: 'Asramam Devaswom Committee',
    status: 'approved',
    tags: ['kollam', 'krishna', 'utsavam', 'kathakali', 'AI'],
  },
  {
    name: 'Lokanarkavu Bhagavathy Theyyam 2025',
    description: 'Lokanarkavu Temple in Vadakara, Kozhikode is one of the oldest Bhagavathy temples in Kerala dating back over 1000 years. The annual Theyyam festival at this temple features the spectacular Chamundi Theyyam, Kari Chamundi, and Raktha Chamundi performances. These divine art forms — performers who are believed to embody the deities themselves — attract devotees from across Malabar. The oracle pronouncements (Arulvakku) given by the Theyyam performers are believed to come directly from the goddess. The 5-day festival is accompanied by traditional percussion concerts.',
    date: new Date('2025-12-15T18:00:00+05:30'),
    endDate: new Date('2025-12-19T06:00:00+05:30'),
    location: {
      address: 'Lokanarkavu Bhagavathy Temple, Vadakara, Kozhikode, Kerala 673101',
      district: 'Kozhikode',
      lat: 11.6029,
      lng: 75.5868,
      placeName: 'Lokanarkavu Temple, Vadakara',
    },
    category: 'Cultural',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Theyyam_Kerala.jpg/1200px-Theyyam_Kerala.jpg'],
    crowd: 'medium',
    attendees: 40000,
    trending: false,
    organizerName: 'Lokanarkavu Devaswom Committee',
    status: 'approved',
    tags: ['theyyam', 'lokanarkavu', 'kozhikode', 'bhagavathy', 'AI'],
  },
  {
    name: 'Ambalapuzha Sree Krishna Temple Palpayasam Festival 2025',
    description: 'Ambalapuzha Sree Krishna Temple in Alappuzha is world-famous for the legendary Palpayasam (rice pudding prasad) offered to Lord Krishna every day without fail for centuries. The temple festival in Karkidakam month celebrates the divine legend of Guruvayurappan defeating a sage in chess and granting the boon of Palpayasam. The 10-day Utsavam features Sopana Sangeetham, Krishnanattam dance performances, and boat races on the nearby Punnamada Lake. The Ashtami Rohini (Janmashtami) Palpayasam distribution draws hundreds of thousands.',
    date: new Date('2025-08-12T05:00:00+05:30'),
    endDate: new Date('2025-08-21T22:00:00+05:30'),
    location: {
      address: 'Ambalapuzha Sree Krishna Temple, Ambalapuzha, Alappuzha, Kerala 688561',
      district: 'Alappuzha',
      lat: 9.3820,
      lng: 76.3553,
      placeName: 'Ambalapuzha Sree Krishna Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ambalapuzha_Krishna_temple.jpg/1200px-Ambalapuzha_Krishna_temple.jpg'],
    crowd: 'high',
    attendees: 250000,
    trending: false,
    organizerName: 'Ambalapuzha Devaswom',
    organizerPhone: '+91-477-2272370',
    status: 'approved',
    tags: ['ambalapuzha', 'palpayasam', 'krishna', 'janmashtami', 'AI'],
  },
  {
    name: 'Nenmara-Vallangi Vela Festival 2025',
    description: 'The Nenmara-Vallangi Vela is one of the grandest and most colourful temple festivals in Palakkad district. Two rival temple groups — Nenmara and Vallangi — compete in an elaborate elephant pageant and Vela (fireworks) competition. The event spans 2 days with over 30 caparisoned elephants on each side performing the Kuda Mela (umbrella exchange) to traditional Panchavadyam drum ensembles. The closing fireworks display lasting 4+ hours is considered one of the finest in Kerala. Hundreds of thousands of spectators attend this unique inter-temple cultural contest.',
    date: new Date('2026-04-04T06:00:00+05:30'),
    endDate: new Date('2026-04-05T05:00:00+05:30'),
    location: {
      address: 'Nenmara-Vallangi, Chittur-Thathamangalam, Palakkad, Kerala 678508',
      district: 'Palakkad',
      lat: 10.5124,
      lng: 76.7266,
      placeName: 'Nenmara Temple Ground',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Nenmara-Vallangi_Vela.jpg/1200px-Nenmara-Vallangi_Vela.jpg'],
    crowd: 'high',
    attendees: 500000,
    trending: true,
    organizerName: 'Nenmara-Vallangi Temple Committee',
    status: 'approved',
    tags: ['nenmara-vallangi', 'vela', 'elephants', 'palakkad', 'AI'],
  },
  {
    name: 'Thiruvillwamala Sreerama Temple Karkidakam Ramayana Masam 2025',
    description: 'Thiruvillwamala Sreerama Temple, one of the very few temples directly dedicated to Lord Rama in Kerala, holds special significance during the month of Karkidakam — the Ramayana month. The entire month is dedicated to daily Ramayana parayanam (recitation), special poojas, and cultural events. The grand Saptaha Yajna (7-day yagna) during the last week of Karkidakam attracts Vedic scholars from across Kerala. The temple, set amidst lush hills and the Bharathapuzha river, provides a serene setting for this deeply spiritual commemoration.',
    date: new Date('2025-07-17T05:00:00+05:30'),
    endDate: new Date('2025-08-16T22:00:00+05:30'),
    location: {
      address: 'Thiruvillwamala Sreerama Temple, Thiruvillwamala, Thrissur, Kerala 680588',
      district: 'Thrissur',
      lat: 10.5483,
      lng: 76.4174,
      placeName: 'Thiruvillwamala Sreerama Temple',
    },
    category: 'Cultural',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Thrissur_district.jpg/1200px-Thrissur_district.jpg'],
    crowd: 'medium',
    attendees: 60000,
    trending: false,
    organizerName: 'Thiruvillwamala Devaswom',
    status: 'approved',
    tags: ['ramayana', 'karkidakam', 'rama', 'thrissur', 'AI'],
  },
  {
    name: 'Mannarsala Sarpabali Nooroum Palum 2025',
    description: 'Mannarsala Nagaraja Temple near Haripad is the largest Nagaraja (serpent deity) temple in Kerala and possibly in all of India, with over 30,000 idols of serpents in its sprawling groves. The annual Ayilyam Pooja (serpent star pooja) and special Nooroum Palum (100-and-milk) offering is one of the most unique rituals in Kerala\'s temple culture. Childless couples and devotees seeking healing undertake the Sarpa Bali ritual here. The spring season festival features Pulluvan Paattu (traditional snake-worship music) and Sarpam Thullal dance.',
    date: new Date('2025-11-12T05:00:00+05:30'),
    endDate: new Date('2025-11-12T22:00:00+05:30'),
    location: {
      address: 'Mannarsala Sree Nagaraja Temple, Mannarsala, Alappuzha, Kerala 690513',
      district: 'Alappuzha',
      lat: 9.2717,
      lng: 76.4472,
      placeName: 'Mannarsala Nagaraja Temple',
    },
    category: 'Cultural',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Mannarasala_Temple.jpg/1200px-Mannarasala_Temple.jpg'],
    crowd: 'high',
    attendees: 100000,
    trending: false,
    organizerName: 'Mannarsala Devaswom',
    organizerPhone: '+91-479-2412303',
    status: 'approved',
    tags: ['mannarsala', 'nagaraja', 'serpent', 'ayilyam', 'haripad', 'AI'],
  },
  {
    name: 'Beemapalli Mosque Urs Festival 2025',
    description: 'The Beemapalli Urs (Saint\'s death anniversary festival) is one of the largest inter-religious gatherings in Kerala, held at Beemapalli Mosque in Thiruvananthapuram. The Urs commemorates the martyrdom of Beema Bibi — a Muslim saint — and draws over 500,000 devotees of all faiths including Hindus, Christians, and Muslims. The event features illuminated processions, qawwali music, Hadya (flag hoisting), and large community feasts. The unique communal harmony of the Beemapalli Urs has made it a symbol of Kerala\'s syncretic culture and tradition.',
    date: new Date('2025-09-06T06:00:00+05:30'),
    endDate: new Date('2025-09-08T23:00:00+05:30'),
    location: {
      address: 'Beemapalli Mosque, Beemapalli, Thiruvananthapuram, Kerala 695008',
      district: 'Thiruvananthapuram',
      lat: 8.4545,
      lng: 76.9353,
      placeName: 'Beemapalli Mosque',
    },
    category: 'Cultural',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Beemapalli_mosque.jpg/1200px-Beemapalli_mosque.jpg'],
    crowd: 'high',
    attendees: 500000,
    trending: false,
    organizerName: 'Beemapalli Juma Masjid Committee',
    organizerPhone: '+91-471-2480022',
    status: 'approved',
    tags: ['beemapalli', 'urs', 'mosque', 'secular', 'thiruvananthapuram', 'AI'],
  },
  {
    name: 'Thrissur Puram Utsavam — Paramekkavu Temple 2025',
    description: 'The 10-day Utsavam of Paramekkavu Bhagavathy Temple in Thrissur traditionally culminates in the spectacular Thrissur Pooram. The mini Paramekkavu Utsavam held independently in Vrischikam month includes Keli (drum invocation), Kudamattam (umbrella exchange), Panchavadyam, and Deeparadhana. This intimate festival gives devotees a close experience with the caparisoned elephants and the magnificent golden parasols without the huge crowds of Pooram day. A 3-day Saptaham bhajan and Harikatha are also organised.',
    date: new Date('2025-11-20T05:00:00+05:30'),
    endDate: new Date('2025-11-29T22:00:00+05:30'),
    location: {
      address: 'Paramekkavu Bhagavathy Temple, Sakthan Nagar, Thrissur, Kerala 680001',
      district: 'Thrissur',
      lat: 10.5266,
      lng: 76.2144,
      placeName: 'Paramekkavu Bhagavathy Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Thrissur_Pooram_2013.jpg/1200px-Thrissur_Pooram_2013.jpg'],
    crowd: 'high',
    attendees: 150000,
    trending: false,
    organizerName: 'Paramekkavu Devaswom',
    organizerPhone: '+91-487-2422752',
    status: 'approved',
    tags: ['paramekkavu', 'thrissur', 'utsavam', 'bhagavathy', 'AI'],
  },
  {
    name: 'Trichambaram Sree Krishna Temple Onam Ashtami 2025',
    description: 'The Trichambaram Sree Krishna Temple Onam celebration in Kannur is a unique tradition where the 10-day Onam festival takes on a deeply spiritual dimension. The temple hosts Thiruvonam special poojas, Onasadya (Onam feast) for 10,000+ devotees, and an Uriyadi (pot-breaking) competition. The Onam Ashtami at this temple is marked by the famous Sree Krishna Vilakku — a 3-hour illumination ceremony where the entire temple complex is lit with thousands of oil lamps. Traditional Onamkali, Vallam Kali (boat race), and Attakkalasam games are also organized in the temple grounds.',
    date: new Date('2025-09-04T05:00:00+05:30'),
    endDate: new Date('2025-09-05T22:00:00+05:30'),
    location: {
      address: 'Trichambaram Sree Krishna Temple, Trichambaram, Kannur, Kerala 670601',
      district: 'Kannur',
      lat: 11.8955,
      lng: 75.3818,
      placeName: 'Trichambaram Sri Krishna Temple',
    },
    category: 'Festival',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Kerala_Onam_Festival.jpg/1200px-Kerala_Onam_Festival.jpg'],
    crowd: 'high',
    attendees: 80000,
    trending: false,
    organizerName: 'Trichambaram Devaswom',
    status: 'approved',
    tags: ['trichambaram', 'onam', 'krishna', 'kannur', 'AI'],
  },
  {
    name: 'Sree Muthappan Temple — Parassinikadavu Thira 2025',
    description: 'The Parassinikadavu Sree Muthappan Temple on the banks of the Valapattanam River in Kannur is one of the most popular shrines in North Kerala. The unique feature of this temple is the daily Thira performance — a ritual where costumed artists embody the deity Muthappan (a syncretic form of Shiva and Vishnu). The Muthappan Thira, unlike other Theyyam forms, is performed every day of the year. The special Annual Mahotsavam in Kumbham month features grand Theyyam performances lasting 48 hours, elephant procession, Thidambu Nritham, fireworks, and cultural events. Muthappan is beloved by people of all faiths.',
    date: new Date('2026-03-05T06:00:00+05:30'),
    endDate: new Date('2026-03-07T22:00:00+05:30'),
    location: {
      address: 'Parassinikadavu Sree Muthappan Temple, Parassinikadavu, Kannur, Kerala 670563',
      district: 'Kannur',
      lat: 11.9672,
      lng: 75.4007,
      placeName: 'Muthappan Temple, Parassinikadavu',
    },
    category: 'Cultural',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Theyyam_Kerala.jpg/1200px-Theyyam_Kerala.jpg'],
    crowd: 'high',
    attendees: 200000,
    trending: false,
    organizerName: 'Parassinikadavu Muthappan Seva Sangham',
    organizerPhone: '+91-497-2782216',
    status: 'approved',
    tags: ['muthappan', 'parassinikadavu', 'theyyam', 'kannur', 'AI'],
  },
];

// ─── Seed Runner ─────────────────────────────────────────────────────────────

async function seed() {
  console.log('🔌 Connecting to MongoDB...');
  await mongoose.connect(MONGO_URI);
  console.log('✅ Connected.');

  // Check for existing AI-seeded events to avoid duplicates
  const existing = await Event.countDocuments({ addedBy: 'AI' });
  if (existing > 0) {
    console.log(`⚠️  Found ${existing} existing AI-tagged events in the database.`);
    console.log('   To re-seed, first delete them: db.events.deleteMany({ addedBy: "AI" })');
    await mongoose.disconnect();
    return;
  }

  // Stamp addedBy:'AI' on every seeded event so they're properly tracked
  const eventsWithTag = events.map(e => ({ ...e, addedBy: 'AI' }));

  console.log(`📥 Inserting ${eventsWithTag.length} Kerala temple events...`);
  const inserted = await Event.insertMany(eventsWithTag);
  console.log(`✅ Successfully inserted ${inserted.length} events!`);
  console.log('   Events stamped with addedBy: "AI" for identification.');

  inserted.forEach(e => console.log(`   ✓ ${e.name}`));

  await mongoose.disconnect();
  console.log('🔌 Disconnected. Done!');
}

seed().catch(err => {
  console.error('❌ Seed failed:', err.message);
  mongoose.disconnect();
  process.exit(1);
});
